### ISSUE TITLE
cannot clone: Operation not permitted

### ISSUE THREAD

**Issue by pinghe** [mgoltzsche/podman-static#70]
When I use it in github actions, I get the following error.
```
cannot clone: Operation not permitted
Error: cannot re-exec process
```

Workflow configuration file  cd.yml:

```
name: test podman
on:
  push:
    branches:
    - main

    # Publish `v1.2.3` tags as releases.
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # image: gitlab/gitlab-runner:alpine3.18
      # image: mgoltzsche/podman:rootless
      # image: mgoltzsche/podman:minimal
      image: mgoltzsche/podman:latest
      options: --privileged 
      # --user podman:podman
    env:
      FORCE_COLOR: 1
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."  
    - name: test podman
      run: |
        whoami
        podman info
```
